### ISSUE TITLE
Pretty much everything the linked addon has that this one doesn't have already

### ISSUE THREAD

**Issue by KekkyShmekky** [Guthen/guthlevelsystem#7]
https://steamcommunity.com/sharedfiles/filedetails/?id=1747642523&searchtext=levelling+system

**Comment by Guthen** [comment]
Well, I think there are only 2 features my system does lack compared to Topher's one which are XP Bonus for Usergroups and Prestige, the others are already implemented.

However, I might add them when I will have enough time to work on this addon. 

Thankx for your suggestion though :p

**Comment by KekkyShmekky** [comment]
Hey so I actually looked through the GitHub and didn't see any mention of custom HUD positioning for clients, so it would also be great to have that in there to work with other HUDs. Thanks!

**Comment by Guthen** [comment]
Hmm yes, the position can only be modified by the server, I'm not sure if players would want to edit the position by themselves but I could add that aswell

**Comment by Guthen** [comment]
I'm listing tasks of this issue todo below to clarify a bit

Todo:
- [x] XP Bonus for Usergroups (see #8)
- [ ] Prestige
- [ ] Client Convars for HUD Position

**Comment by Guthen** [comment]
#8 has just been resolved

**Comment by KekkyShmekky** [comment]
Hey so I noticed players don't get XPs for killing NPCs on this pack even though I tried making it work with this

`if ( not ent:IsNPC() and not ent:IsNextBot() and not scripted_ents.IsBasedOn(ent:GetClass(), "npc_creature_base")) or not take then return end`

https://steamcommunity.com/sharedfiles/filedetails/?id=1516718459

**Comment by Certurix** [comment]
This addon use a custom Class, so yes its not working by default, because its not using the default SNPCS Class of Garry's Mod.

"`if ( not ent:IsNPC() and not ent:IsNextBot() and not scripted_ents.IsBasedOn(ent:GetClass(), "npc_creature_base")) or not take then return end`"
Is this code working?

**Comment by Guthen** [comment]
Hey, you should create a new issue for this problem (since it's mostly already fix, you don't have to, but please report in new issues in the future). I will try to give a look tonight. Thanks for the report :p

**Comment by Guthen** [comment]
Alright, I just made a commit (not so much changes in the code as you can tell) which should fix compatibility with any other mods (in theory). I tested it with the addon you just gave and it works fine now, tell me if it is for you too

**Comment by KekkyShmekky** [comment]
Hey so the fix worked. Thanks!

**Comment by Guthen** [comment]
Nice, no problem :)

**Comment by KekkyShmekky** [comment]
Hey so I recently updated to 1.8.0 and I found that I can't see the addon's HUD anymore for some reason

**Comment by Guthen** [comment]
> Hey so I recently updated to 1.8.0 and I found that I can't see the addon's HUD anymore for some reason

Hey, did you edit anything, like the `sh_config.lua` or the HUD file? If so, ensure that `guthlevelsystem.DrawHUD` is set to `true` & and `guthlevelsystem.SelectedHUD` is set to a correct value (or send what you edit)

**Comment by KekkyShmekky** [comment]
Hey so DrawHUD is set to true and the selected HUD is "default_text"

**Comment by Guthen** [comment]
> Hey so DrawHUD is set to true and the selected HUD is "default_text"

Sounds fine, I have no ideas why it's not working though. Does it do the same if you re-install the mod without touching to the files (even the config files)?

**Comment by KekkyShmekky** [comment]
Hey so I just reinstalled the mod without touching anything at all, and it still doesn't show the HUD.

**Comment by Guthen** [comment]
Hm, that's weird, did you install an other addon (HUD or anything) recently? 

If so, try to remove them or enter this command in your **game**'s console (when you are in your server) to see which one could conflict: `lua_run_cl PrintTable( hook.GetTable()["HUDShouldDraw"] )` (you can send the output here)? 

You have to set the convar `sv_allowcslua 1` in your **server**'s console first. If you find the cause, tell me

**Comment by Guthen** [comment]
@Certurix have the same problem than you and the above idea didn't really helped, so it might be my fault, I will try to figure it out on a local dedicated server, I will inform you on my progress

**Comment by Guthen** [comment]
Just found out that HUD files weren't sent to client upon connection causing the HUD code to not run and to throwing errors.
This issue should be fixed now

**Comment by KekkyShmekky** [comment]
I still can't see the HUD even after a restart. I printed the hook tables via ULX and your hook didn't actually show up anywhere.

**Comment by Guthen** [comment]
So the fix I just made does not work? Do you have any errors while joining your server (check the 'Problems' menu of gmod)? 

For the hooks, if you did it with the ulx luarun command, it's normal that it shows nothing because it's run server-side and not client-side, and server do not handle HUDs. It's why I asked specifically to run it in your game's console

**Comment by KekkyShmekky** [comment]
The ulx gethooktable command is actually meant to be run on players and HUDShouldDraw didn't yield any of your hooks/events even when I ran it on myself.

I also didn't find any errors while joining the server.

**Comment by Guthen** [comment]
Alright, just made a fix thanks to Sidroz on my discord server, it should definitely work. Lemme know

**Comment by KekkyShmekky** [comment]
Hey so the HUD shows, but it doesn't seem to update its position live like before the update.

**Comment by KekkyShmekky** [comment]
[ERROR] addons/guthlevelsystem-master/lua/guthlevelsystem/sv_data.lua:6: attempt to call method 'LSGetData' (a nil value)
  1. __event - addons/guthlevelsystem-master/lua/guthlevelsystem/sv_data.lua:6

**Comment by Guthen** [comment]
> Hey so the HUD shows, but it doesn't seem to update its position live like before the update.

Yes, you also have to save the `cl_hud.lua` to apply your changes in the HUDs

**Comment by KekkyShmekky** [comment]
Tried that with no luck

EDIT: Nvm it works now!

**Comment by Guthen** [comment]
Nice!
